version: '2'
services:
    cebilletterie-app:
        image: cebilletterie
        external_links:
            - cebilletterie-postgresql:postgresql
            - cebilletterie-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/cebilletterie
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    cebilletterie-postgresql:
        extends:
            file: postgresql.yml
            service: cebilletterie-postgresql
    cebilletterie-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: cebilletterie-elasticsearch
